### ISSUE TITLE
[Suggestion] Permissions

### ISSUE THREAD

**Issue by DillonB07** [Ladysnake/Impersonate#10]
Would you be able to add LuckPerms support or config to allow non-opped players to use the command?

**Comment by Pyrofab** [comment]
I assume it's possible, but I'd have to see how that is done.

**Comment by DillonB07** [comment]
I've no idea what you want to do with it, but here is the LuckPerms developer wiki if you are interested in using LuckPerms:
https://luckperms.net/wiki/Developer-API

**Comment by Pyrofab** [comment]
Alright, I used [Fabric Permissions API](https://github.com/lucko/fabric-permissions-api), made this quite easy. I also updated the readme with the new permissions.
