### ISSUE TITLE
Cannot initialize Minecraft on clean Fabric server (injection failure)

### ISSUE THREAD

**Issue by mathiasyde** [Ladysnake/Impersonate#14]
This mod will crash the server, even though the installation steps are followed as described.

Steps to reproduce:
1. Use "Fabric Installer"'s server tab, using loader version 0.11.5 and Minecraft 1.17, download the files, download the server.jar through same installer, generate start scripts.
2. use the provided start.bat file to initialize first time setup, agree to EULA and run same script again
3. Wait until server starts up
4. Put in "impersonate-2.3.0.jar" and "fabric-api-0.35.1+1.17.jar" into the "mods" folder

Terminal output
https://pastebin.com/pwF9HRdu

**Comment by Pyrofab** [comment]
Should have been fixed in 2.3.1.
