### ISSUE TITLE
Where do I reference "impersonator" from? & How do I change what skin to change it to?

### ISSUE THREAD

**Issue by brnfhz** [Ladysnake/Impersonate#16]

**Comment by Pyrofab** [comment]
I'll need more details. Are you using the mod as a player or as a developee ? And did you actually read the description ?

**Comment by StackoverflowEnjoyer** [comment]
I already set up a fabric mod and I tried adding it, everything works except Impersonator and I don!t know why. (Ignore my second question)

**Comment by Pyrofab** [comment]
Ok so you are using the API, it should be fairly straightforward ? You need to pass a GameProfile, which you can get by doing `existingPlayer.getGameProfile()` or `new GameProfile(userName, userUuid)`.

**Comment by brnfhz** [comment]
It suddenly works but the gamerules still don't work I will try to find out why

**Comment by StackoverflowEnjoyer** [comment]
Nvm it works

**Comment by brnfhz** [comment]
Nvm it works now thx
