### ISSUE TITLE
Bewitchment/Illuminations compat

### ISSUE THREAD

**Issue by VoidLock92** [Ladysnake/Impersonate#17]
At the current moment with the last fix in version 17 of Bewitchment illumination particles now get hidden with the spectral bangle properly allowing players to sneak with their particles. I wonder if there is a way to allow polymorph to hide particles also as these give away a players true identity.

The same bit of code identifying a player as invisible might be able to be applied to the polymorph potion without actually making them go invisible. In a sense the player as we knew them is invisible and they look like another.

I'm not sure if this would be better suited for impersonations compatibility. But figured I would share it here as this is what we found on my server with my modpack. Players that impersonate someone else with polymorph must still go and turn off their particles then restart their game to get illumination particles to disappear and not blow their cover.

^^^ This is a copy of what I posted to Bewitchments issues, the creator informed me that if there was to be a fix for this on Bewitchments end that it would be very hacky in their code. So I am hoping that maybe we are able to get something here with compatibility for impersonations to allow illumination particles to be hidden with the minecraft invisibility tag.

**Comment by Pyrofab** [comment]
Ehhh, I can't really use the invisibility flag for that since you are absolutely visible, you just look like someone else. It would be awkward if the game and other mods considered you super stealthy despite you walking around in a player form. I reckon dedicated compatibility between Illuminations and Impersonate would work a bit better ?

**Comment by VoidLock92** [comment]
Maybe yeah, I'm not sure what would be best. I just think it would be awesome :) I am on version 1.16.5 currently BTW since Bewitchment is for 1.16.5. I really hope some form of compatibility can happen, that would be awesome.

**Comment by Pyrofab** [comment]
Ah, most development is happening on 1.17 currently. I *may* do something for 1.16, but really no guarantee there.

**Comment by VoidLock92** [comment]
Yeah I know, I understand that for sure :P I can hope though haha. I will be on 1.17 once Bewitchment is on that version but as my modpack is circled around Bewitchment it is hard. If you do something for 1.16 I would be very grateful if not no hard feelings I will have to wait for 1.17 till we can use our particles.

**Comment by Pyrofab** [comment]
Apologies I couldn't even get my 1.16 environment development to work (and I needed a dedicated illuminations update anyway), so it's only for 1.17. You'll have to wait for Bewitchment to update, but it will be there when it does =)

**Comment by VoidLock92** [comment]
No worries, Thanks so much again for your hard work 👍
