### ISSUE TITLE
Cape doesn't render

### ISSUE THREAD

**Issue by CalXee** [Ladysnake/Impersonate#19]
My friend got the migrator cape but on a server with this mod installed it doesn't render. Removing the mod fixes this issue.

**Comment by Pyrofab** [comment]
Huh. What happens if you enable the `impersonate:fakeCapes` gamerule ?

**Comment by CalXee** [comment]
I cannot get my friend online very frequently. but with that enabled I can impersonate as them and get the Migrator cape.

**Comment by Korinku** [comment]
> 
> 
> Huh. What happens if you enable the `impersonate:fakeCapes` gamerule ?

Yhap, if you set the gamerule to true it works just fine !

**Comment by Pyrofab** [comment]
Then I guess I did that gamerule wrong. Will try to fix that.

**Comment by CammiePone** [comment]
So, was just about to report this bug again, but decided to check if it had been reported before.

Well it's great it's fixed, but you also might want to tag it as 1.17.1 as well on CF, otherwise the launcher doesn't know the mod is updated.
