### ISSUE TITLE
Potential incompatibility with PlayerPig?

### ISSUE THREAD

**Issue by astridos2go** [Ladysnake/Impersonate#24]
Hi, I run a 1.19 server for myself and my friends, and I was hoping to add this mod to the server. I have also recently added the mod [PlayerPig](https://www.curseforge.com/minecraft/mc-mods/playerpig). However, when I tried using the impersonation command, it crashed the server, and then would not let me join subsequently, until I restarted the server without this mod enabled. 

I was not sure if it was because of the PlayerPig mod, or because of this mod that the issue was occuring, and wanted to reach out to see if you knew anything about this?

I have also attached the [error log](https://pastebin.com/7iSLyBcV). Please let me know if there's anything else I can do to help!

**Comment by Pyrofab** [comment]
Looks like the chat mixin is not being applied somehow... I doubt it's the PlayerPig mod causing it though, could you maybe try to find the minimal amount of mods required to cause this crash ?

**Comment by Eman-3600** [comment]
Just did a singleplayer test with just the two mods installed. No crash. Definitely more than just the PlayerPig mod leading to this.

**Comment by astridos2go** [comment]
I will look into it more when I have more free time. Hopefully over the weekend

**Comment by astridos2go** [comment]
The latest version of impersonate resolves this issue
