### ISSUE TITLE
Fabric 1.19 - Bewitchment: Polymorph crash

### ISSUE THREAD

**Issue by jaredniegas** [Ladysnake/Impersonate#26]
I use a Polymorph potion, which leads to the server crashing and it has to restart. When I try joining again, it crashes. It's fixed when I remove the Polymorph effect from my NBT data, though.

I was told by the (I assume lead) Bewitchment dev to report to you all here. :)
[crash-2022-07-20_21.40.42-server.txt](https://github.com/Ladysnake/Impersonate/files/9150851/crash-2022-07-20_21.40.42-server.txt)

**Comment by Pyrofab** [comment]
Yep, was informed by Moriiya of this issue, it looks like an incompatibility with ServerCore.

**Comment by jaredniegas** [comment]
Oh okay, thanks for the info. I'll get rid of it then. Thanks again for the help!
