### ISSUE TITLE
Issue: Fabric Discord Link compatibility

### ISSUE THREAD

**Issue by TheMinesweep3r** [Ladysnake/Impersonate#3]
Using Fabric Discord Link with this mod, the discord chat link is able to see both usernames as admins see when the game rule is enabled. Even disabling this option does not fix this issue. This is most likely because the server logs always display both names. Would it be possible to add a config option to enable/disable this.

**Comment by Pyrofab** [comment]
Sure, I can add a gamerule to disable server logs revealing impersonations.
