### ISSUE TITLE
LuckPerms commands not working

### ISSUE THREAD

**Issue by RoKat6** [Ladysnake/Impersonate#30]
I'm planning to add impersonate to my minecraft server, and added LuckPerms aswell so that I could use the custom Impersonate commands that are in the mod for players that wouldn't be opped. I went to test that it would work but when I tried to add that node to the default group, it wouldn't work and would just say "LuckPerms 5.4.25 installed" or something like that. I looked into the issue and it said I needed some extra plugins for it to work. But those plugins are just that. Plugins. In order for Impersonate to work, I would have to be on fabric, and these extra plugins didn't support a fabric verison. Any ideas on how to get the depenancies for fabric?

**Comment by Pyrofab** [comment]
Looks like I should in fact have looked at this earlier, the compatibility code has in fact been broken for over 6 months. There should not be any need for plugins though, you can setup basic permissions with just what's explained on this page : https://luckperms.net/wiki/Usage

In any case, I confirmed things are working again in version 2.9.0.
