### ISSUE TITLE
popular skins not working. 

### ISSUE THREAD

**Issue by cosplgay** [Ladysnake/Impersonate#8]
I am trying to make a cinematic with the dreamSMP members skins. Although when i type 
``impersonate disguise as GeorgeNotFound`` 
it will not set me as his skin. The same things happens with all of the other members. It seems like it is famous people that it wont allow me to get the skin. In chat it does say 

> Started impersonating GeorgeNotFound

and my character does its little spin, but it doesnt set me as his skin. im not sure why it does this.

It also will sometimes set my skin to a Dream skin, but not george's. Im not sure why it does that.

but thank you for reading this! it is an awesome mod and it has served me great!

**Comment by DillonB07** [comment]
You could try [FabricTailor](https://www.curseforge.com/minecraft/mc-mods/fabrictailor), [Taterzens](https://www.curseforge.com/minecraft/mc-mods/taterzens) or [Carpet Mod](https://www.curseforge.com/minecraft/mc-mods/carpet) (use the /player command) instead.

**Comment by Pyrofab** [comment]
Akshually, FabricTailor's `/skin set player` command suffers from exactly the same issue as we both use the same code ^^

**Comment by DillonB07** [comment]
Yes I knew that. I completely forgot about it when I wrote it though.

**Comment by Pyrofab** [comment]
And now, it should actually work =)
